name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Install pytest
    #   run: |
    #     pip install pytest
    # - name: Run tests
    #   run: |
    #     python -m pytest

  docker:

    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: hashit
    - name: Log in to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        # push: ${{ github.event_name != 'pull_request' }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
        provenance: true
        sbom: true